import Head from 'next/head';
import styles from '@take-home-task/styles/Home.module.css';
import { useInterval, useAppDispatch } from '@take-home-task/hooks';
import { storeWrapper } from '@take-home-task/store';
import { ExchangeRatesTableWrap, insertRatesThunk } from '@take-home-task/features/exchangeRates';

/**
 * Can be moved to environment variable if
 * environments have different needs for request frequency
 * or to be able to re-deploy without making changes to the code.
 */
const FETCH_EXCHANGE_RATES_REQUEST_DELAY_MS = 60000;

export default function Home() {
  const dispatch = useAppDispatch();

  useInterval(() => {
    dispatch(insertRatesThunk());
  }, FETCH_EXCHANGE_RATES_REQUEST_DELAY_MS);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ExchangeRatesTableWrap />
      </main>
    </>
  )
}

Home.getInitialProps = storeWrapper.getInitialPageProps((store) => async () => {
  await store.dispatch(insertRatesThunk());
  return {};
});